### ISSUE TITLE
Is this SDK `the best way` to use Adobe Analytics?

### ISSUE THREAD

**Issue by Francisc** [Adobe-Marketing-Cloud/marketing-cloud-javascript-sdk#9]
Hello,

Like the subject says, is this SDK "the best" (to be read as "the official") way of using Adobe Analytics?

Also, where can I read about what kind of params I can pass to `MarketingCloud.makeRequest`.
The readme file for this repo doesn't make that clear.

Thanks.

**Comment by garyr** [comment]
Francisc, this is the only JS SDK published by Adobe to use against the Analytics API. It works very well, but you are right, it is sparsely documented. We can point you to another repo which has implemented the library and you can see it in action: https://github.com/Adobe-Marketing-Cloud/analytics-realtime-dashboard-example (see lesson_2.html). You will also need to populate config.js with your own API credentials

**Comment by Francisc** [comment]
Awesome, thank you.
